name: Update Telegram IP

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-ip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Run IP updater
      run: |
        python get_ip.py

    # Paso nuevo: Reemplazar placeholders con secrets
    - name: Replace secrets in PHP file
      run: |
        sed -i "s/{{TELEGRAM_TOKEN}}/${{ secrets.TELEGRAM_TOKEN }}/g" timbre.php
        sed -i "s/{{TELEGRAM_CHAT_ID}}/${{ secrets.TELEGRAM_CHAT_ID }}/g" timbre.php
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Force PHP file update
      run: |
        sed -i "s/api.telegram.org:443:0.0.0.0/api.telegram.org:443:$(cat last_ip.txt)/g" timbre.php
        
    - name: Upload files via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /htdocs/

    - name: Debug IP
      run: |
      echo "IP actual: $(cat last_ip.txt)"
      echo "Contenido de timbre.php:"
      cat timbre.php | grep "CURLOPT_RESOLVE"

    - name: Enviar notificación a Telegram
      if: ${{ failure() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "⚠️ Fallo al actualizar IP de Telegram"
