name: Update Telegram IP

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta diariamente a medianoche (UTC)
  workflow_dispatch:     # Permite ejecución manual

jobs:
  update-ip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run IP updater
      run: |
        python get_ip.py
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -A
        git commit -m "Actualizar IP de Telegram"
        git push
